### ISSUE TITLE
java.lang.NoSuchMethodError: No direct method <init>(ILjava/lang/Object;Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)

### ISSUE THREAD

**Issue by arianatri** [DanielMartinus/Konfetti#193]
dialog fragment code : 

```Java
public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        root_view = inflater.inflate(R.layout.dialog_payment_success_salon, container, false);

        ((ImageView) root_view.findViewById(R.id.card_logo)).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                konfettiView.build()
                        .addColors(Color.YELLOW, Color.GREEN, Color.MAGENTA)
                        .setDirection(0.0, 359.0)
                        .setSpeed(1f, 5f)
                        .setFadeOutEnabled(true)
                        .setTimeToLive(2000L)
                        .addShapes(Shape.Square.INSTANCE, Shape.Circle.INSTANCE)
                        .addSizes(new Size(12, 5f))
                        .setPosition(konfettiView.getX() + konfettiView.getWidth() / 2, konfettiView.getY() + konfettiView.getHeight() / 3)
                        .streamFor(300, 5000L);

            }
        });
    return root_view;
}
```

logcat erorr :
2020-09-12 10:31:26.874 30091-30091/com..XXXX/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.XXXX.XXX, PID: 30091
    java.lang.NoSuchMethodError: No direct method <init>(ILjava/lang/Object;Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V in class Lkotlin/jvm/internal/FunctionReferenceImpl; or its super classes (declaration of 'kotlin.jvm.internal.FunctionReferenceImpl' appears in /data/app/com.XXX.XXXX-0iMy12wP_nXJDZT24C3MaQ==/base.apk)
        at nl.dionsegijn.konfetti.emitters.RenderSystem$1.<init>(Unknown Source:10)
        at nl.dionsegijn.konfetti.emitters.RenderSystem.<init>(RenderSystem.kt:39)
        at nl.dionsegijn.konfetti.ParticleSystem.startRenderSystem(ParticleSystem.kt:276)
        at nl.dionsegijn.konfetti.ParticleSystem.streamFor(ParticleSystem.kt:235)
        at com.XXX.XXXX.utils.DialogPaymentSuccessFragment$2.onClick(DialogPaymentSuccessFragment.java:58)
        at android.view.View.performClick(View.java:7869)
        at android.view.View.performClickInternal(View.java:7838)
        at android.view.View.access$3600(View.java:886)
        at android.view.View$PerformClick.run(View.java:29362)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8019)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Comment by DanielMartinus** [comment]
@arianatri looks like you've not included the kotlin stdlib in your Java project. See this section on how to fix that: https://github.com/DanielMartinus/Konfetti#java-project

**Comment by madsys11** [comment]
I had the same issue.
It was fixed after changing from kotlin 1.3.72 to 1.4.10

**Comment by DanielMartinus** [comment]
Assuming this one is fixed with two possible solutions presented in this thread. @arianatri please re-open this issue when you have any further questions.

**Comment by Arushi129** [comment]
Hi, I have the same error on my KMM project.

java.lang.NoSuchMethodError: No direct method (Ljava/lang/String;Lkotlinx/serialization/internal/GeneratedSerializer;I)V in class Lkotlinx/serialization/internal/SerialClassDescImpl; or its super classes (declaration of 'kotlinx.serialization.internal.SerialClassDescImpl' appears in /data/app/com.example.mykmmclient12april-eQ9TG4Mg_9sDGC-WYU26Eg==/base.apk)
at org.openapitools.client.models.Order$$serializer.(Order.kt:28)
at org.openapitools.client.models.Order$Companion.serializer(Unknown Source:0)
at org.openapitools.client.infrastructure.ApiClient$Companion.setMappers(ApiClient.kt:64)
at org.openapitools.client.infrastructure.ApiClient$Companion.access$setMappers(ApiClient.kt:57)
at org.openapitools.client.infrastructure.ApiClient$serializer$2.invoke(ApiClient.kt:41)
at org.openapitools.client.infrastructure.ApiClient$serializer$2.invoke(ApiClient.kt:28)
at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
at org.openapitools.client.infrastructure.ApiClient.getSerializer(Unknown Source:2)
at org.openapitools.client.infrastructure.ApiClient.jsonRequest(ApiClient.kt:148)
at org.openapitools.client.apis.StoreApi.placeOrder(StoreApi.kt:171)
at com.example.mykmmclient12april.MainActivity.callApi(MainActivity.kt:44)
at com.example.mykmmclient12april.MainActivity$onCreate$1.invokeSuspend(MainActivity.kt:29)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:193)

Order Class -
@serializable
data class Order (
@SerialName(value = "id") val id: kotlin.Long? = null,
@SerialName(value = "petId") val petId: kotlin.Long? = null,
@SerialName(value = "quantity") val quantity: kotlin.Int? = null,
@SerialName(value = "shipDate") val shipDate: kotlin.String? = null,
/* Order Status */
@SerialName(value = "status") val status: Order.Status? = null,
@SerialName(value = "complete") val complete: kotlin.Boolean? = null
) {

Environment:

Kotlin version: [1.3.72]
serialization plugin version:[0.12.0]
IDE version [Android Studio 4.1.1]
gradle version:[6.5]

I doesn't want to update the kotlin and plugin version as it may affect my other projects. Please help.
