### ISSUE TITLE
Error on trying to show

### ISSUE THREAD

**Issue by MBoberski** [DanielMartinus/Konfetti#199]
I updated version from 1.2.0 to 1.2.4 and I get:

```
2020-09-22 13:01:42.832 24672-24672/com.listonic.baitads E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.listonic.baitads, PID: 24672
    java.lang.NoSuchMethodError: No direct method <init>(ILjava/lang/Object;Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V in class Lkotlin/jvm/internal/FunctionReferenceImpl; or its super classes (declaration of 'kotlin.jvm.internal.FunctionReferenceImpl' appears in /data/app/com.listonic.baitads-aGwdJWnHzGcz2xNlEW-ucw==/base.apk!classes5.dex)
        at nl.dionsegijn.konfetti.emitters.RenderSystem$1.<init>(Unknown Source:10)
        at nl.dionsegijn.konfetti.emitters.RenderSystem.<init>(RenderSystem.kt:39)
        at nl.dionsegijn.konfetti.ParticleSystem.startRenderSystem(ParticleSystem.kt:258)
        at nl.dionsegijn.konfetti.ParticleSystem.streamFor(ParticleSystem.kt:217)
```

when trying to run:

```
       bait_ads_konfetti.build()
            .addColors(
                ContextCompat.getColor(
                    applicationContext,
                    R.color.bait_ads_confetti_aquamarine_color
                ),
                ContextCompat.getColor(
                    applicationContext,
                    R.color.bait_ads_confetti_violet_red_color
                ),
                ContextCompat.getColor(
                    applicationContext,
                    R.color.bait_ads_confetti_energy_yellow_color
                ),
                ContextCompat.getColor(applicationContext, R.color.bait_ads_confetti_seance_color)
            )
            .setDirection(CONFETTI_DIRECTION_MIN, CONFETTI_DIRECTION_MAX)
            .setSpeed(CONFETTI_MIN_SPEED, CONFETTI_MAX_SPEED)
            .setFadeOutEnabled(true)
            .setTimeToLive(CONFETTI_TIME_TO_LIVE)
            .addShapes(Shape.Square, Shape.Circle)
            .addSizes(Size(CONFETTI_SIZE_12), Size(CONFETTI_SIZE_16, CONFETTI_MASS))
            .setPosition(
                CONFETTI_MIN_X,
                screenWidth + CONFETTI_MAX_X,
                CONFETTI_MIN_Y,
                CONFETTI_MAX_Y
            )
            .streamFor(CONFETTI_PARTICLES_PER_SECOND, CONFETTI_EMITTING_TIME)
```

**Comment by DanielMartinus** [comment]
Hey @MBoberski, could it perhaps have to do something with this issue and comment? https://github.com/DanielMartinus/Konfetti/issues/193#issuecomment-691765015

**Comment by DanielMartinus** [comment]
Please reopen this issue if you have any questions
