### ISSUE TITLE
NoClassDefFoundError kotlin/jvm/internal/Intrinsics

### ISSUE THREAD

**Issue by kwiky** [DanielMartinus/Konfetti#47]
Hi,

This error occures with the new version 1.1.1
```
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
	at nl.dionsegijn.konfetti.ParticleSystem.<init>(ParticleSystem.kt)
	at nl.dionsegijn.konfetti.KonfettiView.build(KonfettiView.kt:39)
```

1.1.0 is OK.

**Comment by kwiky** [comment]
Thank you @DanielMartinus 👍

**Comment by ash2osh** [comment]
+1

**Comment by DanielMartinus** [comment]
Could you try if newly released version 1.1.2 works fine?

**Comment by kwiky** [comment]
It looks ok !
Thanks @DanielMartinus

**Comment by kwiky** [comment]
Nope, my bad, it happens again on my CI : 
```
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
	at nl.dionsegijn.konfetti.ParticleSystem.<init>(ParticleSystem.kt)
	at nl.dionsegijn.konfetti.KonfettiView.build(KonfettiView.kt:39)
```

**Comment by kwiky** [comment]
Just tested again with 1.1.2-rc1 and this error is still here
```
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
	at nl.dionsegijn.konfetti.ParticleSystem.<init>(ParticleSystem.kt)
	at nl.dionsegijn.konfetti.KonfettiView.build(KonfettiView.kt:39)
```

**Comment by DanielMartinus** [comment]
It would help if I could play with a sample project that has this problem. I'm not able to recreate it and thus find out and test what is going on.

**Comment by arpitsharmagit** [comment]
I have same issue please find below log.

`AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.magicwin.app.magicwin, PID: 9093
                  java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
                      at nl.dionsegijn.konfetti.KonfettiView.onDraw(Unknown Source:2)
                      at android.view.View.draw(View.java:19291)
                      at android.view.View.updateDisplayListIfDirty(View.java:18241)
                      at android.view.View.draw(View.java:19019)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4026)
                      at android.view.View.draw(View.java:19294)
                      at android.view.View.updateDisplayListIfDirty(View.java:18241)
                      at android.view.View.draw(View.java:19019)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4026)
                      at android.view.View.updateDisplayListIfDirty(View.java:18232)
                      at android.view.View.draw(View.java:19019)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4026)
                      at android.view.View.updateDisplayListIfDirty(View.java:18232)
                      at android.view.View.draw(View.java:19019)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4026)
                      at android.view.View.updateDisplayListIfDirty(View.java:18232)
                      at android.view.View.draw(View.java:19019)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4026)
                      at android.view.View.updateDisplayListIfDirty(View.java:18232)
                      at android.view.View.draw(View.java:19019)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4026)
                      at android.view.View.draw(View.java:19294)
                      at com.android.internal.policy.DecorView.draw(DecorView.java:789)
                      at android.view.View.updateDisplayListIfDirty(View.java:18241)
                      at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:680)
                      at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:686)
                      at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:794)
                      at android.view.ViewRootImpl.draw(ViewRootImpl.java:3131)
                      at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2935)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2488)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1514)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7259)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1039)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:851)
                      at android.view.Choreographer.doFrame(Choreographer.java:742)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1025)
                      at android.os.Handler.handleCallback(Handler.java:790)
                      at android.os.Handler.dispatchMessage(Handler.java:99)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6753)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.jvm.internal.Intrinsics" on path: DexPathList[[zip file "/data/app/com.magicwin.app.magicwin-Khvuul-szEK3kG9poibTKA==/base.apk", zip file "/data/app/com.magicwin.app.magicwin-Khvuul-szEK3kG9poibTKA==/split_lib_dependencies_apk.apk", zip file "/data/app/com.magicwin.app.magicwin-Khvuul-szEK3kG9poibTKA==/split_lib_resources_apk.apk", zip file "/data/app/com.magicwin.app.magicwin-Khvuul-szEK3kG9poibTKA==/split_lib_slice_0_apk.apk", zip file "/data/app/com.magicwin.app.magicwin-Khvuul-szEK3kG9poibTKA==/split_lib_slice_1_apk.apk", zip file "/data/app/com.magicwin.app.magicwin-Khvuul-szEK3kG9poibTKA==/split_lib_slice_2_apk.apk", zip file "/data/app/com.magicwin.app.magicwin-Khvuul-szEK3kG9poibTKA==/split_lib_slice_3_apk.apk", zip file "/data/app/com.magicwin.app.magicwin-Khvuul-szEK3kG9poibTKA==/split_lib_slice_4_apk.apk", zip file "/data/app/com.magicwin.app.magicwin-Khvuul-szEK3kG9poibTKA==/split_lib_slice_5_apk.apk", zip file "/data/app/com.magicwin.app.magicwin-Khvuul-szEK3kG9poibTKA==/split_lib_slice_6_apk.apk", zip file "/data/app/com.magicwin.app.magicwin-Khvuul-szEK3kG9poibTKA==/split_lib_slice_7_apk.apk", zip file "/data/app/com.magicwin.app.magicwin-Khvuul-szEK3kG9poibTKA==/split_lib_slice_8_apk.apk", zip file "/data/app/com.magicwin.app.magicwin-Khvuul-szEK3kG9poibTKA==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.magicwin.app.magicwin-Khvuul-szEK3kG9poibTKA==/lib/arm64, /system/lib64, /system/vendor/lib64]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                      	... 49 more
                  	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.magicwin.app.magicwin-Khvuul-szEK3kG9poibTKA==/split_lib_resources_apk.apk
                      at dalvik.system.DexFile.openDexFileNative(Native Method)
                      at dalvik.system.DexFile.openDexFile(DexFile.java:353)
                      at dalvik.system.DexFile.<init>(DexFile.java:100)
                      at dalvik.system.DexFile.<init>(DexFile.java:74)
                      at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
                      at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
                      at dalvik.system.DexPathList.<init>(DexPathList.java:157)
                      at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
                      at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
                      at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
                      at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
                      at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
                      at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:35)
                      at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:703)
                      at android.app.LoadedApk.getClassLoader(LoadedApk.java:737)
                      at android.app.LoadedApk.getResources(LoadedApk.java:965)
                      at android.app.ContextImpl.createAppContext(ContextImpl.java:2302)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5864)
                      at android.app.ActivityThread.-wrap1(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1755)
                      at android.os.Handler.dispatchMessage(Handler.java:106)
                      		... 5 more
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.magicwin.app.magicwin, PID: 9093
                  java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
                      at nl.dionsegijn.konfetti.KonfettiView.onDraw(Unknown Source:2)
                      at android.view.View.draw(View.java:19291)
                      at android.view.View.updateDisplayListIfDirty(View.java:18241)
                      at android.view.View.draw(View.java:19019)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4026)
                      at android.view.View.draw(View.java:19294)
                      at android.view.View.updateDisplayListIfDirty(View.java:18241)
                      at android.view.View.draw(View.java:19019)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4026)
                      at android.view.View.updateDisplayListIfDirty(View.java:18232)
                      at android.view.View.draw(View.java:19019)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4026)
                      at android.view.View.updateDisplayListIfDirty(View.java:18232)
                      at android.view.View.draw(View.java:19019)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4026)
                      at android.view.View.updateDisplayListIfDirty(View.java:18232)
                      at android.view.View.draw(View.java:19019)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4026)
                      at android.view.View.updateDisplayListIfDirty(View.java:18232)
                      at android.view.View.draw(View.java:19019)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4026)
                      at android.view.View.draw(View.java:19294)
                      at com.android.internal.policy.DecorView.draw(DecorView.java:789)
                      at android.view.View.updateDisplayListIfDirty(View.java:18241)
                      at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:680)
                      at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:686)
                      at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:794)
                      at android.view.ViewRootImpl.draw(ViewRootImpl.java:3131)
                      at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2935)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2488)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1514)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7259)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1039)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:851)
                      at android.view.Choreographer.doFrame(Choreographer.java:742)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1025)
                      at android.os.Handler.handleCallback(Handler.java:790)
                      at android.os.Handler.dispatchMessage(Handler.java:99)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6753)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.jvm.internal.Intrinsics" on path: DexPathList[[zip file "/data/app/com.magicwin.app.magicwin-Khvuul-szEK3kG9poibTKA==/base.apk", zip file "/data/app/com.magicwin.app.magicwin-Khvuul-szEK3kG9poibTKA==/split_lib_dependencies_apk.apk", zip file "/data/app/com.magicwin.app.magicwin-Khvuul-szEK3kG9poibTKA==/split_lib_resources_apk.apk", zip file "/data/app/com.magicwin.app.magicwin-Khvuul-szEK3kG9poibTKA==/split_lib_slice_0_apk.apk", zip file "/data/app/com.magicwin.app.magicwin-Khvuul-szEK3kG9poibTKA==/split_lib_slice_1_apk.apk", zip file "/data/app/com.magicwin.app.magicwin-Khvuul-szEK3kG9poibTKA==/split_lib_slice_2_apk.apk", zip file "/data/app/com.magicwin.app.magicwin-Khvuul-szEK3kG9poibTKA==/split_lib_slice_3_apk.apk", zip file "/data/app/com.magicwin.app.magicwin-Khvuul-szEK3kG9poibTKA==/split_lib_slice_4_apk.apk", zip file "/data/app/com.magicwin.app.magicwin-Khvuul-szEK3kG9poibTKA==/split_lib_slice_5_apk.apk", zip file "/data/app/com.magicwin.app.magicwin-Khvuul-szEK3kG9poibTKA==/split_lib_slice_6_apk.apk", zip file "/data/app/com.magicwin.app.magicwin-Khvuul-szEK3kG9poibTKA==/split_lib_slice_7_apk.apk", zip file "/data/app/com.magicwin.app.magicwin-Khvuul-szEK3kG9poibTKA==/split_lib_slice_8_apk.apk", zip file "/data/app/com.magicwin.app.magicwin-Khvuul-szEK3kG9poibTKA==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.magicwin.app.magicwin-Khvuul-szEK3kG9poibTKA==/lib/arm64, /system/lib64, /system/vendor/lib64]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                      	... 49 more
                  	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.magicwin.app.magicwin-Khvuul-szEK3kG9poibTKA==/split_lib_resources_apk.apk
                      at dalvik.system.DexFile.openDexFileNative(Native Method)
                      at dalvik.system.DexFile.openDexFile(DexFile.java:353)
                      at dalvik.system.DexFile.<init>(DexFile.java:100)
                      at dalvik.system.DexFile.<init>(DexFile.java:74)
                      at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
                      at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
                      at dalvik.system.DexPathList.<init>(DexPathList.java:157)
                      at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
                      at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
                      at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
                      at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
                      at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
                      at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:35)
                      at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:703)
                      at android.app.LoadedApk.getClassLoader(LoadedApk.java:737)
                      at android.app.LoadedApk.getResources(LoadedApk.java:965)
                      at android.app.ContextImpl.createAppContext(ContextImpl.java:2302)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5864)
                      at android.app.ActivityThread.-wrap1(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1755)
                      at android.os.Handler.dispatchMessage(Handler.java:106)
                      		... 5 more
W/OPDiagnose: getService:OPDiagnoseService NULL
D/OSTracker: OS Event: crash
D/AbstractTracker: Event success
`

**Comment by kwiky** [comment]
@DanielMartinus finally fixed by manually adding the kotlin-stdlib-jdk7 (which was missing in graph dependencies) in my `build.gradle` file
```
    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.2.41'
    implementation 'nl.dionsegijn:konfetti:1.1.2'
```

**Comment by DanielMartinus** [comment]
@kwiky thanks a lot @kwiky, I'll update the readme accordingly!

**Comment by bihanmahadewa** [comment]
So does this still work for 1.1.3 ?
