### ISSUE TITLE
OutOfMemoryError 

### ISSUE THREAD

**Issue by davidmigloz** [DanielMartinus/Konfetti#49]
Hi, thanks for your awesome library.

I got a crash report of an OutOfMemoryError that was caused by Konfetti.

Device: Samsung Galaxy S7
Android version: 7.0
Trace:
```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 4861960 byte allocation with 2445416 free bytes and 2MB until OOM
       at java.util.Arrays.copyOf(Arrays.java:3231)
       at java.util.Arrays.copyOf(Arrays.java:3204)
       at java.util.ArrayList.grow(ArrayList.java:249)
       at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:223)
       at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:215)
       at java.util.ArrayList.add(ArrayList.java:441)
       at nl.dionsegijn.konfetti.emitters.RenderSystem.addConfetti(RenderSystem.kt:1034)
       at nl.dionsegijn.konfetti.emitters.RenderSystem$1.invoke(RenderSystem.kt:1030)
       at nl.dionsegijn.konfetti.emitters.StreamEmitter.createParticle(StreamEmitter.kt:2057)
       at nl.dionsegijn.konfetti.KonfettiView.nl.dionsegijn.konfetti.emitters.RenderSystem.render(KonfettiView.kt:2046)
       at android.view.View.draw(View.java:18319)
       at android.view.View.updateDisplayListIfDirty(View.java:17297)
       at android.view.View.draw(View.java:18081)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
       at android.view.View.updateDisplayListIfDirty(View.java:17292)
       at android.view.View.draw(View.java:18081)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
       at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1254)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
       at android.view.View.updateDisplayListIfDirty(View.java:17292)
       at android.view.View.draw(View.java:18081)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
       at android.view.View.updateDisplayListIfDirty(View.java:17292)
       at android.view.View.draw(View.java:18081)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
       at android.view.View.updateDisplayListIfDirty(View.java:17292)
       at android.view.View.draw(View.java:18081)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
       at android.view.View.updateDisplayListIfDirty(View.java:17292)
       at android.view.View.draw(View.java:18081)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
       at android.view.View.updateDisplayListIfDirty(View.java:17292)
       at android.view.View.draw(View.java:18081)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
       at android.view.View.draw(View.java:18322)
       at com.android.internal.policy.DecorView.draw(DecorView.java:854)
       at android.view.View.updateDisplayListIfDirty(View.java:17297)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:666)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:672)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:780)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:3112)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2908)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2502)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1509)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7051)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
       at android.view.Choreographer.doCallbacks(Choreographer.java:702)
       at android.view.Choreographer.doFrame(Choreographer.java:638)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6692)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

And my setup was:
```
binding.konfetti.build() 
    .addColors(Color.rgb(239, 115, 47), Color.rgb(161, 44, 46), Color.rgb(39, 71, 134), Color.WHITE) 
    .setSpeed(1f, 3f) 
    .setFadeOutEnabled(true) 
    .setTimeToLive(3000L) 
    .addShapes(Shape.RECT, Shape.CIRCLE) 
    .addSizes(new Size(12, 5)) 
    .setDirection(0.0, 180.0) 
    .setPosition(0, (float) binding.mainContent.getWidth(), -100F, -100F) 
    .stream(70, 3000L);
```

I just got one crash report, so I guess is some edge case.

Cheers!

**Comment by davidmigloz** [comment]
It's the only crash report that I got from that user and the only crash report where Konfetti was involved (Konfetti was running just one day). When the crash happened, the device had 24% of the RAM free. The screen where I was showing the confetti was pretty simple, I cannot think of anything that could be clogging up the memory there.

**Comment by SammyOdenhoven** [comment]
Same here. Samsung Galaxy S7 Edge with Android 7.0. 1.19 GB free RAM according to Crashlytics.
```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 4861960 byte allocation with 339688 free bytes and 331KB until OOM
       at java.util.Arrays.copyOf(Arrays.java:3231)
       at java.util.Arrays.copyOf(Arrays.java:3204)
       at java.util.ArrayList.grow(ArrayList.java:249)
       at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:223)
       at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:215)
       at java.util.ArrayList.add(ArrayList.java:441)
       at nl.dionsegijn.konfetti.emitters.RenderSystem.addConfetti(RenderSystem.kt:34)
       at nl.dionsegijn.konfetti.emitters.RenderSystem.access$addConfetti(RenderSystem.kt:16)
       at nl.dionsegijn.konfetti.emitters.RenderSystem$1.invoke(RenderSystem.kt:30)
       at nl.dionsegijn.konfetti.emitters.RenderSystem$1.invoke(RenderSystem.kt:16)
       at nl.dionsegijn.konfetti.emitters.StreamEmitter.createParticle(StreamEmitter.kt:57)
       at nl.dionsegijn.konfetti.emitters.StreamEmitter.createConfetti(StreamEmitter.kt:46)
       at nl.dionsegijn.konfetti.emitters.RenderSystem.render(RenderSystem.kt:46)
       at nl.dionsegijn.konfetti.KonfettiView.onDraw(KonfettiView.kt:47)
       at android.view.View.draw(View.java:18313)
       at android.view.View.updateDisplayListIfDirty(View.java:17291)
       at android.view.View.draw(View.java:18075)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
       at android.view.View.updateDisplayListIfDirty(View.java:17286)
       at android.view.View.draw(View.java:18075)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
       at android.view.View.updateDisplayListIfDirty(View.java:17286)
       at android.view.View.draw(View.java:18075)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
       at android.view.View.updateDisplayListIfDirty(View.java:17286)
       at android.view.View.draw(View.java:18075)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
       at android.view.View.updateDisplayListIfDirty(View.java:17286)
       at android.view.View.draw(View.java:18075)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
       at android.view.View.updateDisplayListIfDirty(View.java:17286)
       at android.view.View.draw(View.java:18075)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
       at android.view.View.draw(View.java:18316)
       at com.android.internal.policy.DecorView.draw(DecorView.java:850)
       at android.view.View.updateDisplayListIfDirty(View.java:17291)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:666)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:672)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:780)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:3103)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2899)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2493)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1493)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7040)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
       at android.view.Choreographer.doCallbacks(Choreographer.java:702)
       at android.view.Choreographer.doFrame(Choreographer.java:638)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6688)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

**Comment by DanielMartinus** [comment]
I've ran the memory profiler for a while trying to seek any weird instances perhaps being retained. Though to be honest, as far as I can see everything seems to be garbage collected as expected. 

@SammyOdenhoven can you tell me more about the setup of Konfetti in your app? The configuration you used, are you streaming or bursting etc? Its nice to have something to compare with @davidmigloz his setup.

**Comment by DanielMartinus** [comment]
Closing this for now since I haven't had more reports. Please open a new issue when the same problem reoccurs.
