### ISSUE TITLE
Getting No Class Found Error With 1.1.2

### ISSUE THREAD

**Issue by rajasekaranm** [DanielMartinus/Konfetti#58]
Hi,
I unable to play animation after updating gradle `1.1.0` to `1.1.2` .

**Note :**  I'm using java

**Error Log :**

`  Process: com.test.test.dev, PID: 26786
    java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
        at nl.dionsegijn.konfetti.ParticleSystem.<init>(ParticleSystem.kt)
        at nl.dionsegijn.konfetti.KonfettiView.build(KonfettiView.kt:39)
        at com.test.test.ui.alert.InfoAlertFragment.onPlayAnimation(InfoAlertFragment.java:148)
        at com.test.test.ui.alert.InfoAlertFragment.onViewCreated(InfoAlertFragment.java:118)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1439)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
        at android.os.Handler.handleCallback(Handler.java:746)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5443)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.jvm.internal.Intrinsics" on path: DexPathList[[zip file "/data/app/com.test.test.dev-1/base.apk", zip file "/data/app/com.test.test.dev-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.test.test.dev-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.test.test.dev-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.test.test.dev-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.test.test.dev-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.test.test.dev-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.test.test.dev-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.test.test.dev-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.test.test.dev-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.test.test.dev-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.test.test.dev-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.test.test.dev-1/lib/arm, /data/app/com.test.test.dev-1/base.apk!/lib/armeabi-v7a, /data/app/com.test.test.dev-1/split_lib_dependencies_apk.apk!/lib/armeabi-v7a, /data/app/com.test.test.dev-1/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/com.test.test.dev-1/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/com.test.test.dev-1/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/com.test.test.dev-1/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/com.test.test.dev-1/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/com.test.test.dev-1/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/com.test.test.dev-1/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/com.test.test.dev-1/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/com.test.test.dev-1/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/com.test.test.dev-1/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at nl.dionsegijn.konfetti.ParticleSystem.<init>(ParticleSystem.kt) 
        at nl.dionsegijn.konfetti.KonfettiView.build(KonfettiView.kt:39) 
        at com.test.test.ui.alert.InfoAlertFragment.onPlayAnimation(InfoAlertFragment.java:148) 
        at com.test.test.ui.alert.InfoAlertFragment.onViewCreated(InfoAlertFragment.java:118) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1439) 
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827) 
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797) 
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596) 
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383) 
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338) 
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245) 
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703) 
        at android.os.Handler.handleCallback(Handler.java:746) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5443) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
    	Suppressed: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
    		at java.lang.Class.classForName
`

**Comment by DanielMartinus** [comment]
Hi @rajasekaranm, please check this issue for more info: https://github.com/DanielMartinus/Konfetti/issues/47

You're probably missing the kotlin stdlib. You'll have to add the following to your dependencies:
`implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.2.41'`
